export default {
  "index": "Overview",
  "concept-erc-20-approvals-the-forgotten-attack-surface": "ERC-20 Approvals: The Forgotten Attack Surface",
  "concept-thorchain-vault-churn-and-asgard-migration": "THORChain Vault Churn and Asgard Migration",
  "principle-a-smart-contract-interaction-is-a-lead-not-an-endpoint": "A Smart Contract Interaction Is a Lead, Not an Endpoint",
  "principle-understand-the-protocol-before-you-conclude": "Understand the Protocol Before You Conclude",
  "framework-asset-tracing-methodologies": "Asset-Tracing Methodologies for Commingled Funds (PIFO, LIBR, LIFO, FIFO, Pari Passu, Rolling Charge)",
  "framework-service-choke-points-what-each-can-give-you": "Service Choke-Points: What Each Service Type Can Give You",
  "workflow-blockchain-explorer-review-procedure": "Blockchain Explorer Review Procedure",
  "workflow-forensic-method-decision-tree": "Forensic Method Selection Decision Tree",
  "workflow-non-explorer-bridge-correlation": "Non-Explorer Bridge Correlation",
  "workflow-transaction-tracing-decision-tree-and-endpoint-classification": "Transaction Tracing Decision Tree and Endpoint Classification",
  "workflow-traversing-ambiguous-peel-chains-with-a-wallet-fingerprint": "Traversing an Ambiguous Peel Chain with a Wallet Fingerprint",
  "workflow-wallet-review-procedure": "Wallet Review Procedure",
  "tactic-bitcoin-op-return-bridge-signal": "Bitcoin OP_RETURN as a Cross-Chain Signal",
  "tactic-coinjoin-mixer-detection": "CoinJoin / Mixer Detection",
  "tactic-coinjoin-implementation-signatures": "CoinJoin Implementation Signatures",
  "tactic-consolidation-addresses-and-tiered-intermediary-groups": "Consolidation Addresses and Tiered Intermediary Groups",
  "tactic-cooperating-instant-exchanges-as-pivot-points": "Cooperating Instant Exchanges as Pivot Points",
  "tactic-cross-chain-bridge-swap-analysis": "Cross-Chain / Bridge & Swap Analysis",
  "tactic-dating-a-block-height-without-an-archive-node": "Dating a Block Height Without an Archive Node",
  "tactic-decode-cross-chain-destination-address": "Decoding a Cross-Chain Destination Address from Input Data",
  "tactic-document-a-token-transfer-by-network-standard-and-contract": "Document a Token Transfer by Network, Standard, and Contract",
  "tactic-etherscan-advanced-filter-by-date": "Etherscan Advanced Filter for Point-in-Time Review",
  "tactic-evm-event-logs-and-decoding-calldata": "EVM Event Logs & Decoding Calldata",
  "tactic-exchange-passthrough-one-to-one-deposit-withdrawal-matching": "Exchange Pass-Through Detection by One-to-One Deposit and Withdrawal Matching",
  "tactic-filter-by-size-scrape-llm-summarise": "Filter-by-Size + Scrape + LLM Summarise",
  "tactic-finding-a-bitcoin-transaction-by-its-op-return": "Finding a Bitcoin Transaction by Its OP_RETURN",
  "tactic-mint-style-bridges-pivot-to-counterparty-graph-analysis": "Mint-Style Bridges: Pivot to Counterparty-Graph Analysis",
  "tactic-peeling-chain-analysis": "Peeling Chain Analysis",
  "tactic-post-mixer-bitcoin-tracing": "Post-Mixer Bitcoin Tracing",
  "tactic-protocol-housekeeping-vs-incident": "Protocol Housekeeping vs Incident",
  "tactic-router-and-multicall-traffic-read-swap-events-exclude-mev": "Router & Multicall Traffic: Read Swap Events, Exclude MEV",
  "tactic-smart-contract-defi-tracing": "Smart Contract / DeFi Protocol Tracing",
  "tactic-taint-analysis": "Taint Analysis (Taint Tracing)",
  "tactic-temporal-timing-correlation": "Temporal / Timing Correlation Analysis",
  "tactic-temporal-analysis-to-defeat-obfuscation": "Temporal Analysis to Defeat Obfuscation",
  "tactic-time-and-value-analysis": "Time-and-Value Analysis",
  "tactic-trace-intent-bridges-via-public-explorer": "Trace an Intent-Based Bridge (NEAR Intents) via Its Public Explorer",
  "tactic-transaction-graph-analysis": "Transaction Graph Analysis (TGA)",
  "tactic-value-and-block-window-candidate-search": "Value-and-Block-Window Candidate Search",
  "checklist-evm-multi-chain-tracing-essentials": "EVM Multi-Chain Tracing Essentials",
  "checklist-when-to-stop-tracing": "Know When to Stop Tracing",
  "caution-liquidity-pool-deposit-ends-asset-identity": "A Liquidity Pool Deposit Ends Asset Identity",
  "caution-cross-chain-correlation-edge-cases-and-failure-modes": "Cross-Chain Correlation Edge Cases & Failure Modes",
  "caution-evm-proxies-read-the-right-source": "EVM Proxies: Read the Right Source",
  "caution-vendor-risk-scores-disagree": "Vendor Risk Scores Disagree, and a Mixer Lowers Them",
  "reference-thorchain-memo-grammar-on-bitcoin": "THORChain Memo Grammar on Bitcoin",
}
