export default {
  "index": "Overview",
  "concept-erc-20-approvals-the-forgotten-attack-surface": "ERC-20 Approvals -- The Forgotten Attack Surface",
  "workflow-forensic-method-decision-tree": "Forensic Method Selection Decision Tree",
  "workflow-non-explorer-bridge-correlation": "Non-Explorer Bridge Correlation",
  "tactic-coinjoin-mixer-detection": "CoinJoin / Mixer Detection",
  "tactic-cooperating-instant-exchanges-as-pivot-points": "Cooperating Instant Exchanges as Pivot Points",
  "tactic-cross-chain-bridge-swap-analysis": "Cross-Chain / Bridge & Swap Analysis",
  "tactic-etherscan-advanced-filter-by-date": "Etherscan Advanced Filter for Point-in-Time Review",
  "tactic-evm-event-logs-and-decoding-calldata": "EVM Event Logs & Decoding Calldata",
  "tactic-filter-by-size-scrape-llm-summarise": "Filter-by-Size + Scrape + LLM Summarise",
  "tactic-mint-style-bridges-pivot-to-counterparty-graph-analysis": "Mint-Style Bridges -- Pivot to Counterparty-Graph Analysis",
  "tactic-peeling-chain-analysis": "Peeling Chain Analysis",
  "tactic-post-mixer-bitcoin-tracing": "Post-Mixer Bitcoin Tracing",
  "tactic-router-and-multicall-traffic-read-swap-events-exclude-mev": "Router & Multicall Traffic -- Read Swap Events, Exclude MEV",
  "tactic-smart-contract-defi-tracing": "Smart Contract / DeFi Protocol Tracing",
  "tactic-taint-analysis": "Taint Analysis (Taint Tracing)",
  "tactic-temporal-timing-correlation": "Temporal / Timing Correlation Analysis",
  "tactic-temporal-analysis-to-defeat-obfuscation": "Temporal Analysis to Defeat Obfuscation",
  "tactic-transaction-graph-analysis": "Transaction Graph Analysis (TGA)",
  "checklist-evm-multi-chain-tracing-essentials": "EVM Multi-Chain Tracing Essentials",
  "caution-cross-chain-correlation-edge-cases-and-failure-modes": "Cross-Chain Correlation Edge Cases & Failure Modes",
  "caution-evm-proxies-read-the-right-source": "EVM Proxies -- Read the Right Source",
}
