export default {
  "index": "Overview",
  "concept-wallet-clustering-and-heuristics": "Wallet Clustering and Heuristics",
  "principle-multiple-attribution-sources": "Never Trust a Single Source of Attribution",
  "framework-attribution-confidence-levels": "Attribution Confidence Levels",
  "workflow-attribution-procedure-seven-steps": "Attribution Procedure (Seven Steps)",
  "workflow-crypto-address-attribution-process": "Crypto Address Attribution Process",
  "tactic-address-clustering-cioh": "Address Clustering (Common-Input-Ownership Heuristic)",
  "tactic-arkham-attribution-visualizer": "Arkham for Attribution and Visualization",
  "tactic-change-address-utxo-heuristics": "Change-Address Heuristics (UTXO Analysis)",
  "tactic-combined-timelines-turning-tracing-into-attribution": "Combined Timelines: Turning Tracing into Attribution",
  "tactic-vasp-kyc-correlation": "Exchange / VASP KYC Correlation",
  "tactic-gas-funding-analysis-to-cluster-controlled-addresses": "Gas-Funding Analysis to Cluster Controlled Addresses",
  "tactic-illicit-vs-licit-transaction-behaviour-profile": "Illicit vs Licit Transaction Behaviour Profile",
  "tactic-view-a-wallets-exposure-with-impersonator-xyz": "View a Wallet's Exposure with impersonator.xyz",
  "tactic-wallet-fingerprinting-transaction-parameters": "Wallet Fingerprinting from Transaction Parameters",
  "checklist-advanced-attribution-techniques": "Advanced Attribution Techniques",
  "checklist-bitcoin-utxo-clustering-heuristics": "Bitcoin UTXO Clustering Heuristics",
  "checklist-clustering-exchange-accounts-from-subpoenaed-records": "Clustering Exchange Accounts From Subpoenaed Records",
  "checklist-verify-a-landmark-address-before-you-trust-it": "Verify a Landmark Address Before You Trust It",
  "caution-address-labels-are-chain-specific": "Address Labels Are Chain-Specific",
  "caution-address-poisoning": "Address Poisoning Attack",
  "caution-change-address-heuristic-failure-modes": "Change-Address Heuristic Failure Modes",
  "caution-confirmation-bias-misleading-data": "Confirmation Bias and Misleading On-Chain Data",
  "caution-self-verified-contract-name-label-spoofing": "Self-Verified Contract Names Can Forge a Trace-Stopping Label",
  "reference-attribution-indicator-categories-and-evidentiary-value": "Attribution Indicator Categories and Relative Evidentiary Value",
  "reference-vasp-types-and-what-each-interaction-means": "VASP Types and What Each Interaction Means",
}
