// GENERATED by scripts/migrate-kb.mjs -- do not edit by hand.
// Landing-page counts, derived from knowledge-base/ so they stay in sync.
export const KB_NOTE_COUNT = 138
export const KB_TOPIC_COUNT = 8
