export default {
  "index": "Overview",
  "concept-freezable-vs-non-freezable-assets": "Freezable vs Non-Freezable Crypto Assets",
  "concept-impersonation-and-kiosk-onramp-scams": "Impersonation Scams and the Crypto-Kiosk On-Ramp",
  "concept-the-scope-triangle": "The Scope Triangle",
  "concept-type-a-vs-type-b-investigation-entry-points": "Type A vs Type B: Where the Investigation Starts",
  "principle-case-tractability-when-to-decline": "Case Tractability: When to Decline",
  "principle-identify-predicate-typology-first": "Identify the Predicate Typology First",
  "principle-manage-both-digital-footprints-opsec": "Manage Both Digital Footprints (OPSEC)",
  "principle-scope-the-engagement-in-writing": "Scope the Engagement in Writing",
  "framework-five-investigation-goal-types": "Five Investigation Goal Types",
  "framework-five-investigation-output-types": "Five Investigation Output Types",
  "framework-investigation-risk-categories-mitigations": "Investigation Risk Categories & Mitigations",
  "framework-pi-response-priority": "PI Response Priority: Freeze, Monitor, Predict, OSINT",
  "framework-recovery-budget-tiers-by-asset-value": "Recovery Budget Tiers by Asset Value",
  "framework-six-core-investigation-questions": "Six Core Investigation Questions",
  "framework-integrated-onchain-offchain-forensic-framework": "The Integrated On-Chain and Off-Chain Forensic Framework",
  "framework-the-recovery-fusion-cell": "The Recovery Fusion Cell",
  "framework-cim-six-operational-phases": "The Six Operational Phases of the Cryptocurrency Investigation Methodology",
  "framework-cim-six-principles": "The Six Principles of the Cryptocurrency Investigation Methodology",
  "framework-six-step-crypto-recovery-framework": "The Six-Step Crypto Recovery Framework",
  "framework-due-diligence-types": "Types of Due Diligence",
  "framework-wf-sop-ws-chk-ref-document-architecture": "WF / SOP / WS / CHK / REF Document Architecture",
  "workflow-case-opening-procedure": "Case Opening Procedure",
  "workflow-the-5-stage-investigation-process": "The 5-Stage Investigation Process",
  "tactic-beginner-investigation-approach": "Beginner Investigation Approach",
  "tactic-controlled-test-transactions-for-ground-truth": "Controlled Test Transactions as Ground Truth",
  "tactic-exchange-tiers-and-the-escalation-clock": "Exchange Tiers and the Escalation Clock",
  "tactic-exchange-freeze-email": "Freezing Funds with an Exchange Email",
  "tactic-monitoring-addresses-with-alerts": "Monitoring Addresses with Alerts",
  "tactic-obsidian-case-management-workflow": "Obsidian Case-Management Workflow",
  "tactic-ofac-sanction-screening": "Screening Addresses Against OFAC Sanctions",
  "tactic-translate-stakeholder-wants-into-investigable-questions": "Translate Stakeholder Wants into Investigable Questions",
  "checklist-crypto-crime-typology-catalogue": "Crypto Crime Typology Catalogue",
  "checklist-first-hour-case-control": "First Hour Case Control Checklist",
  "checklist-five-intake-red-flags": "Five Intake Red Flags",
  "checklist-freeze-circumvention-techniques-and-countermeasures": "Freeze Circumvention Techniques and Countermeasures",
  "checklist-intake-triage-checklist": "Intake Triage Checklist",
  "checklist-investigator-opsec": "Investigator OPSEC Checklist",
  "checklist-post-seizure-monitoring-periods": "Post-Seizure Monitoring Periods by Asset Type",
  "checklist-pre-incident-recovery-readiness": "Pre-Incident Recovery Readiness",
  "checklist-pre-investigation-readiness-checklist": "Pre-Investigation Readiness Checklist",
  "checklist-sanctions-screening-a-bitcoin-cluster": "Sanctions Screening a Bitcoin Cluster",
  "checklist-surface-level-fast-wins": "Surface-Level Fast Wins",
  "checklist-first-24-hours-of-a-crypto-theft": "The First 24 Hours of a Crypto Theft",
  "checklist-victim-artifact-intake": "Victim Artifact Intake: Getting the Starting Point Right",
  "caution-five-recovery-pitfalls": "Five Recovery Pitfalls",
}
