export default {
  "index": "Overview",
  "concept-freezable-vs-non-freezable-assets": "Freezable vs Non-Freezable Crypto Assets",
  "concept-the-scope-triangle": "The Scope Triangle",
  "principle-case-tractability-when-to-decline": "Case Tractability -- When to Decline",
  "principle-manage-both-digital-footprints-opsec": "Manage Both Digital Footprints (OPSEC)",
  "framework-five-investigation-goal-types": "Five Investigation Goal Types",
  "framework-five-investigation-output-types": "Five Investigation Output Types",
  "framework-investigation-risk-categories-mitigations": "Investigation Risk Categories & Mitigations",
  "framework-pi-response-priority": "PI Response Priority: Freeze, Monitor, Predict, OSINT",
  "framework-six-core-investigation-questions": "Six Core Investigation Questions",
  "workflow-the-5-stage-investigation-process": "The 5-Stage Investigation Process",
  "tactic-beginner-investigation-approach": "Beginner Investigation Approach",
  "tactic-exchange-freeze-email": "Freezing Funds with an Exchange Email",
  "tactic-obsidian-case-management-workflow": "Obsidian Case-Management Workflow",
  "tactic-ofac-sanction-screening": "Screening Addresses Against OFAC Sanctions",
  "tactic-translate-stakeholder-wants-into-investigable-questions": "Translate Stakeholder Wants into Investigable Questions",
  "checklist-five-intake-red-flags": "Five Intake Red Flags",
  "checklist-intake-triage-checklist": "Intake Triage Checklist",
  "checklist-investigator-opsec": "Investigator OPSEC Checklist",
  "checklist-pre-investigation-readiness-checklist": "Pre-Investigation Readiness Checklist",
  "checklist-sanctions-screening-a-bitcoin-cluster": "Sanctions Screening a Bitcoin Cluster",
  "checklist-surface-level-fast-wins": "Surface-Level Fast Wins",
}
