export default {
  "index": "Overview",
  "concept-chain-hopping": "Chain Hopping / Cross-Chain Bridging",
  "concept-defi-layering": "DeFi Layering",
  "concept-dormancy-time-delay-laundering": "Dormancy / Time-Delay Laundering",
  "concept-drainer-kit-and-known-actor-pattern-recognition": "Drainer-Kit & Known-Actor Pattern Recognition",
  "concept-gambling-platform-laundering": "Gambling Platform Laundering",
  "concept-gather-scatter": "Gather-Scatter",
  "concept-mixing-tumbling": "Mixing / Tumbling (CoinJoin)",
  "concept-money-mule-networks": "Money Mule Networks",
  "concept-nested-services-omnibus-wallets": "Nested Services / Omnibus Wallets",
  "concept-otc-guarantee-market-laundering": "OTC Brokering / Underground Guarantee Markets",
  "concept-peel-chain": "Peel Chain",
  "concept-privacy-coin-conversion": "Privacy Coin Conversion",
  "concept-real-world-asset-conversion": "Real-World Asset Conversion",
  "concept-structuring-smurfing": "Structuring / Smurfing",
  "concept-synthetic-shell-kyc": "Synthetic / Shell KYC Onboarding",
  "concept-tornado-renbtc-laundering-pattern": "Tornado Cash to RenBTC Cross-Chain Laundering Pattern",
  "concept-wash-trading": "Wash Trading (incl. NFTs)",
  "principle-single-indicator-is-a-lead-not-proof": "Single Indicator Is a Lead, Not Proof",
  "framework-breaking-obfuscation-five-part-strategy": "Breaking Obfuscation -- Five-Part Strategy",
  "framework-why-threat-actors-obfuscate-five-motivations": "Why Threat Actors Obfuscate -- Five Motivations",
  "checklist-cross-chain-obfuscation-categories": "Cross-Chain Obfuscation Categories",
  "checklist-offchain-behavioral-red-flags": "Off-Chain Behavioral Red-Flag Checklist",
  "checklist-onchain-laundering-pattern-catalogue": "On-Chain Laundering Pattern Catalogue",
  "checklist-on-chain-obfuscation-categories": "On-Chain Obfuscation Categories",
  "caution-monero-is-the-practical-ceiling-of-on-chain-attribution": "Monero Is the Practical Ceiling of On-Chain Attribution",
  "example-case-tornado-cash-round-trip-resolved-by-address-reuse": "Case: Tornado Cash Round-Trip Resolved by Address Reuse",
  "mixers": "Mixers & Tumblers",
}
