export default {
  "index": "Overview",
  "concept-blockchain-as-evidence-custody-infrastructure": "Blockchain as Evidence Custody Infrastructure",
  "concept-glass-box-attribution": "Glass Box Attribution",
  "concept-working-with-law-enforcement": "Working with Law Enforcement: Capacity, Speed, and Cross-Sector Coalitions",
  "principle-describe-laundering-in-phases-when-transactions-cannot-be-counted": "Describe Laundering in Phases When the Transactions Cannot Be Counted",
  "principle-fact-witness-vs-expert-witness": "Fact Witness vs Expert Witness",
  "principle-replicable-handover-reports": "Handover Reports Must Be Replicable",
  "principle-separate-on-chain-fact-from-inference": "Separate On-Chain Fact from Analytical Inference",
  "framework-admissibility-the-three-gates": "Admissibility: The Three Gates",
  "framework-compelling-vasp-disclosure-legal-process": "Compelling VASP Disclosure: The Legal-Process Ladder",
  "framework-court-tested-attribution-evidence-types": "Court-Tested Attribution Evidence Types",
  "framework-five-evidence-preservation-principles": "Five Evidence Preservation Principles",
  "framework-four-parallel-recovery-avenues": "Four Parallel Recovery Avenues",
  "framework-court-credible-forensic-report-six-characteristics": "Six Characteristics of a Court-Credible Forensic Report",
  "framework-the-analysis-standard-four-block-write-up": "The Analysis Standard: Four-Block Write-Up",
  "framework-forfeiture-complaint-tracing-narrative": "The Forfeiture-Complaint Tracing Narrative (DOJ Civil Forfeiture Structure)",
  "framework-three-layer-blockchain-evidence-model": "The Three Layers of Blockchain Evidence",
  "workflow-evidence-preservation-procedure": "Evidence Preservation Procedure",
  "workflow-seizing-crypto-assets": "Seizing Crypto: Devices, VASP Accounts, and the Agency Wallet",
  "tactic-anchor-findings-with-temporal-qualifiers": "Anchor Every Finding With a Temporal Qualifier",
  "tactic-articulating-no-legitimate-economic-purpose": "Articulating No Legitimate Economic Purpose",
  "tactic-calibrate-testimony-language": "Calibrate Your Testimony Language",
  "checklist-chain-of-custody-by-evidence-type": "Chain of Custody by Evidence Type",
  "checklist-crypto-artifacts-on-a-seized-device": "Crypto Artifacts on a Seized Device",
  "checklist-custody-log-the-six-questions": "Custody Log: The Six Questions",
  "checklist-evidence-preservation": "Evidence Preservation Checklist",
  "checklist-identifying-crypto-in-the-field": "Identifying Cryptocurrency in the Field",
  "checklist-known-weaknesses-to-disclose-in-a-forensic-report": "Known Weaknesses to Disclose in a Forensic Report",
  "checklist-preserve-the-analysis-for-reconstruction": "Preserve the Analysis, Not Just the Finding",
  "checklist-reviewing-an-opposing-forensic-report": "Reviewing an Opposing Forensic Report",
  "checklist-prosecution-engagement-before-report": "Three Conversations With the Prosecutor Before You Draft",
  "checklist-vasp-records-what-to-request": "VASP Records: What to Request and What Exists",
  "checklist-what-to-collect-on-chain-and-off-chain-evidence": "What to Collect: On-Chain & Off-Chain Evidence",
  "caution-commercial-analytics-and-the-daubert-challenge": "Commercial Analytics & the Daubert Challenge",
  "caution-lawful-collection-pretexting-poisons-evidence": "Lawful Collection: Pretexting Poisons the Evidence",
  "caution-public-attribution-legal-risk": "The Risk of Public Attribution",
  "caution-time-decay-of-crypto-evidence": "Time-Decay of Crypto Evidence",
  "example-daloia-v-persons-unknown-methodology-failure": "D'Aloia v Persons Unknown: When the Methodology Fails, Not the Trace",
  "reference-expert-evidence-rules-usa-uk-australia": "Expert Evidence Rules: USA, UK, Australia",
  "reference-forensic-standards-and-legal-instruments-for-crypto-cases": "Forensic Standards and Legal Instruments for Crypto Cases",
  "reference-recovery-jurisdictions-and-crypto-case-law": "Recovery Jurisdictions and Crypto Case Law",
}
