export default {
  "index": "Overview",
  "concept-glass-box-attribution": "Glass Box Attribution",
  "concept-working-with-law-enforcement": "Working with Law Enforcement: Capacity, Speed, and Cross-Sector Coalitions",
  "principle-fact-witness-vs-expert-witness": "Fact Witness vs Expert Witness",
  "principle-replicable-handover-reports": "Handover Reports Must Be Replicable",
  "principle-separate-on-chain-fact-from-inference": "Separate On-Chain Fact from Analytical Inference",
  "framework-admissibility-the-three-gates": "Admissibility: The Three Gates",
  "framework-compelling-vasp-disclosure-legal-process": "Compelling VASP Disclosure: The Legal-Process Ladder",
  "framework-court-tested-attribution-evidence-types": "Court-Tested Attribution Evidence Types",
  "framework-five-evidence-preservation-principles": "Five Evidence Preservation Principles",
  "framework-three-layer-blockchain-evidence-model": "The Three Layers of Blockchain Evidence",
  "tactic-calibrate-testimony-language": "Calibrate Your Testimony Language",
  "checklist-chain-of-custody-by-evidence-type": "Chain of Custody by Evidence Type",
  "checklist-custody-log-the-six-questions": "Custody Log: The Six Questions",
  "checklist-evidence-preservation": "Evidence Preservation Checklist",
  "checklist-prosecution-engagement-before-report": "Three Conversations With the Prosecutor Before You Draft",
  "checklist-what-to-collect-on-chain-and-off-chain-evidence": "What to Collect: On-Chain & Off-Chain Evidence",
  "caution-commercial-analytics-and-the-daubert-challenge": "Commercial Analytics & the Daubert Challenge",
  "caution-lawful-collection-pretexting-poisons-evidence": "Lawful Collection: Pretexting Poisons the Evidence",
  "caution-public-attribution-legal-risk": "The Risk of Public Attribution",
  "caution-time-decay-of-crypto-evidence": "Time-Decay of Crypto Evidence",
}
