export default {
  "index": "Overview",
  "concept-passive-vs-active-osint": "Passive vs Active OSINT",
  "definition-what-osint-is": "What OSINT Is",
  "principle-osint-paints-the-jigsaw": "OSINT Paints the Picture on the Transaction Jigsaw",
  "framework-osint-to-on-chain-pivots-five-shapes": "OSINT-to-On-Chain Pivots -- Five Shapes",
  "framework-source-reliability-grading-nato-stanag-2511": "Source Reliability Grading (NATO STANAG 2511)",
  "workflow-the-osint-lifecycle": "The OSINT Lifecycle",
  "tactic-darknet-market-osint-correlation": "Darknet Market & OSINT Correlation",
  "tactic-google-dorking": "Google Dorking for Attribution",
  "checklist-common-osint-source-categories": "Common OSINT Source Categories",
  "checklist-google-dorking-operators-for-investigators": "Google Dorking Operators for Investigators",
  "checklist-key-osint-techniques-for-crypto-investigators": "Key OSINT Techniques for Crypto Investigators",
  "example-silk-road-altoid-google-dork": "Silk Road and the Altoid Google Dork",
}
